src/sysinfo.py
src/utils.py

Refactored for simplicity and added more system info

Refactored for simplicity and added more system info

---

src/sysinfo.py

Changed EntryRow to ActionRow, added ok and important symbols

Changed EntryRow to ActionRow, added ok and important symbols

---

src/manualtest.py

Added implementation for manualtest

Added implementation for manualtest

---

src/check_packages.py
src/finaltest.py

Add check packages page for finaltest. Currently static content, further implementation to be done later.

Add check packages page for finaltest. Currently static content, further implementation to be done later.

---

src/check_packages.py
src/finaltest.py
src/package_lists.py
src/utils.py

feat: Implemented check_snaps and check_debs

feat: Implemented check_snaps and check_debs

---

src/check_packages.py
src/finaltest.py
src/finaltestcomplete.py
src/knum.py
src/landscape.py
src/manualtest.py
src/osload.py
src/osloadcomplete.py
src/sysinfo.py

Abstract the header out of the page and set it based on a new title property set on each page

Abstract the header out of the page

---

src/knum.py
src/utils.py

fix: Don't allow hostname to be set to blank

fix: Don't allow hostname to be set to blank

---

src/sysinfo.py
src/utils.py

feat: Implemented battery_capacity in sysinfo and utils and implemented scrolled window in sysinfo to accommodate batteries

feat: Implemented battery_capacity in sysinfo and utils

---

src/check_packages.py

* Don't duplicate packages on navigation
* Delete existing rows to ensure we don't leak extra buttons

fix: Don't duplicate packages on navigation

---

src/finaltest.py
src/osload.py

fix: Updated default window size

fix: Updated default window size

---

src/check_packages.py

chore: Disabled fix package feature until implemented

chore: Disabled fix package feature until implemented

---

src/deviceinfo.py
src/kramden-device.in

feat: Implemented deviceinfo.py and kramden-device.in

feat: Implemented deviceinfo.py and kramden-device.in

---

src/utils.py

If file isn't readable, make it readable and don't prompt for a password on every call to is_registered

feat: No root for is registered

---

src/css/style.css
src/sysinfo.py

Fix: Add contrast to widgets that fail in sysinfo. Fixes #32

Fix: Add contrast to widgets that fail in sysinfo. Fixes #32

---

src/knum.py
src/landscape.py
src/osload.py
src/sysinfo.py

feat: Added auto-progression for knum and landscape pages. fixes #31

feat: Added auto-progression for knum and landscape pages

---

src/knum.py

feat: on pressing enter run on_set_clicked. fixes #39

feat: on pressing enter run on_set_clicked. fixes #39

---

src/sysinfo.py

fix: fixed duplicated battery code in sysinfo

fix: fixed duplicated battery code in sysinfo

---

src/sysinfo.py

Use a single Adw.ExpanderRow for single battery and multiple batteries. Also populate the battery information in on_shown.

fix: Use a single Adw.ExpanderRow for single battery and multiple batteries. 

---

src/finaltest.py
src/osload.py

fix: Focus the next button fixes: #45

fix: Focus the next button fixes: #45

---

src/manualtest.py

feat: Made manual test rows clickable

feat: Made manual test rows clickable, fixes #47
